|:
| Hello World code which prints the first 22 elements of file on the default out stream
:>
JMP START
:
	#OUT-FILE-STRING --POS--
	CHARS 'UTF-8' ".\\src\\test\\resources\\readfiles\\helloworld.txt\0"
	#OUT-FILE-NAME-SIZE 46
	
>
@START
#GET_IP-POS --POS--
GET_IP AX
SUB AX , #GET_IP-POS
#GET_IP-POS ~DEL
ADD AX , #OUT-FILE-STRING
INT #INT-STREAMS-NEW_IN

|:	AX=FILE_ID
	BX=X
	CX=X
	DX=X |>

MOV DX , AX
MOV AX , 20
INT #INT-MEMORY-ALLOC

|:	AX=MEM-PNTR
	BX=X
	CX=X
	DX=INPUT_FILE-ID |>

MOV CX , AX
MOV BX , 20

INT #INT-STREAMS-READ
|: MOV AX , #INT-STREAMS-READ
INT #INT-STREAMS |>

|:	AX=READ-ELEMENTS
	BX=20
	CX=PNTR
	DX=INPUT_FILE-ID |>

MOV BX , AX
MOV AX , #STD-OUT

|:	AX=STD-OUT
	BX=WRITE-COUNT
	CX=MEM-PNTR
	DX=INPUT_FILE-ID |>

INT #INT-STREAMS-WRITE

|:	AX=WRITTEN-COUNT
	BX=WANTED-WRITE-COUNT
	CX=MEM-PNTR
	DX=INPUT_FILE-ID |>

MOV AX, CX
INT #INT-MEMORY-FREE

|:	AX=FREED-MEM-PNTR
	BX=WANTED-WRITE-COUNT
	CX=FREED-MEM-PNTR
	DX=INTPUT_FILE-ID |>

MOV AX , DX
INT #INT_STREAMS_CLOSE_STREAM
|:	AX=COSED_INTPUT_FILE-ID
	BX=WANTED-WRITE-COUNT
	CX=FREED-MEM-PNTR
	DX=COSED_INTPUT_FILE-ID |>

MOV AX , 0 |> EXIT-SUCCESS
INT #INT-EXIT
