~IF ( #~FOR_ME == 0 )
	~READ_SYM "[THIS]" #ADD~FOR_ME 1 >
~ELSE
	#STR_POS 0
	#STR_LEN 0
~ENDIF

MOV X00, STD_OUT
MOV X01, STR_LEN
#REL_POS ( STR_POS - --POS-- )
LEA X02, REL_POS
#REL_POS ~DEL
INT INT_STREAMS_WRITE
XOR X00, X00
INT INT_EXIT

#EXP~STR_POS --POS--
: CHARS 'UTF-8' "hello primitive world\n" >
#EXP~STR_LEN ( --POS-- - STR_POS )
