package de.hechler.patrick.codesprachen.primitive.disassemble.enums;
public class CmdNums {
	
	public static final int MOV = 0x01;
	public static final int ADD = 0x02;
	public static final int SUB = 0x03;
	public static final int MUL = 0x04;
	public static final int DIV = 0x05;
	public static final int AND = 0x06;
	public static final int OR = 0x07;
	public static final int XOR = 0x08;
	public static final int NOT = 0x09;
	public static final int NEG = 0x0A;
	public static final int LSH = 0x0B;
	public static final int RLSH = 0x0C;
	public static final int RASH = 0x0D;
	public static final int DEC = 0x0E;
	public static final int INC = 0x0F;
	public static final int JMP = 0x10;
	public static final int JMPEQ = 0x11;
	public static final int JMPNE = 0x12;
	public static final int JMPGT = 0x13;
	public static final int JMPGE = 0x14;
	public static final int JMPLT = 0x15;
	public static final int JMPLE = 0x16;
	public static final int JMPCS = 0x17;
	public static final int JMPCC = 0x18;
	public static final int JMPZS = 0x19;
	public static final int JMPZC = 0x1A;
	public static final int CALL = 0x20;
	public static final int CMP = 0x21;
	public static final int RET = 0x22;
	public static final int INT = 0x23;
	public static final int PUSH = 0x24;
	public static final int POP = 0x25;
	public static final int SET_IP = 0x26;
	public static final int SET_SP = 0x27;
	public static final int GET_IP = 0x28;
	public static final int GET_SP = 0x29;
	public static final int GET_INTS = 0x2A;
	public static final int SET_INTS = 0x2B;
	public static final int IRET = 0x2C;
	public static final int GET_INTCNT = 0x2D;
	public static final int SET_INTCNT = 0x2E;
	public static final int SWAP = 0x2F;
	public static final int ADDC = 0x30;
	public static final int SUBC = 0x31;
	public static final int ADDFP = 0x32;
	public static final int SUBFP = 0x33;
	public static final int MULFP = 0x34;
	public static final int DIVFP = 0x35;
	public static final int NTFP = 0x36;
	public static final int FPTN = 0x37;
	
}
